### ISSUE TITLE
Draft the layout of the frontend pages

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/phi-deidentifier#16]
## Page 1

This page of the Shiny app allows the user to copy a clinical note, deidentify it and see the deidentified note.

## Extra pages

- Settings?

**Comment by thomasyu888** [comment]
If we autogenerated an R API client with openapi-generator, a shiny frontend could be deployed.

**Comment by tschaffter** [comment]
@thomasyu888 Do you have a reference link? I'll try to have a look at a few types of clients that the openapi-generator supports that could be compatible with the development of web client. I also plan to look at a generator that can create a boilerplate for a react client.

**Comment by tschaffter** [comment]
@cascadianblue This ticket is about drafting what the UI / identify the UI element required and how to organize them in the space of the page. This can be done to some extend independently of the language / framework used for the implementation. Ideally you can come up with a LucidChart preview of what the UI proposal.

**Comment by tschaffter** [comment]
We did most of this task during a discussion with @cascadianblue who has since started to implement the web client.
