### ISSUE TITLE
Return service information

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/phi-deidentifier#23]

**Comment by tschaffter** [comment]
Depends on https://github.com/nlpsandbox/nlpsandbox-schemas/issues/133

**Comment by tschaffter** [comment]
@cascadianblue Here is an example of the Service object returned by the [Data Node](https://github.com/nlpsandbox/data-node).

**Comment by cascadianblue** [comment]
> @cascadianblue Here is an example of the Service object returned by the [Data Node](https://github.com/nlpsandbox/data-node).

The link just goes to the data node repository home page. Did you mean to link to [this](https://github.com/nlpsandbox/data-node/blob/develop/server/openapi_server/controllers/service_controller.py)?

**Comment by tschaffter** [comment]
Here is the [direct link](https://github.com/nlpsandbox/data-node/blob/develop/server/openapi_server/controllers/service_controller.py)
