### ISSUE TITLE
Dockerize the client

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/phi-deidentifier#37]
- [ ] Add a Dockerfile for the client
- [ ] Add the client to the project docker-compose.yml

**Comment by cascadianblue** [comment]
One hurdle in implementing this is adding a header on the back end allowing cross origin requests. Or figuring out some other way around the cross-origin issue without lowering the security standard.

**Comment by cascadianblue** [comment]
How to reproduce the cross-origin problem: [run the client](https://github.com/nlpsandbox/phi-deidentifier#run). Open up the web client at [localhost:3000](localhost:3000) using a web browser with CORS enforcement disabled (see previous doc link). Try de-identifying a note and make sure it works.

Then, open a separate, normal browser window (i.e. with CORS enforcement), go to [localhost:3000](localhost:3000), try to de-identify a note, and watch it fail.

**Comment by tschaffter** [comment]
The client is technically dockerized though it does not work by itself due to CORS origin errors. The solution to this issue is tracked in #45.
