### ISSUE TITLE
Implement JSON Query Save Button

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/phi-deidentifier#39]
Should include short explanation, and alternative copy-able `curl` command version

**Comment by tschaffter** [comment]
The state of the app is now saved in the URL of the app. If the user is interested in grabbing the request body, this information can be found in the browser console. For example on FF:

![image](https://user-images.githubusercontent.com/3056480/106220594-b5e80a00-6190-11eb-8445-40416c14d005.png)

`{"annotationSource":{"resourceSource":{"name":"name"}},"textDateAnnotations":[{"dateFormat":"MM/DD/YYYY","length":10,"start":42,"text":"10/26/2020"},{"dateFormat":"MM/DD/YYYY","length":10,"start":42,"text":"10/26/2020"}],"textPersonNameAnnotations":[{"length":11,"start":42,"text":"Chloe Price"},{"length":11,"start":42,"text":"Chloe Price"}],"textPhysicalAddressAnnotations":[{"addressType":"city","length":11,"start":42,"text":"Seattle"},{"addressType":"city","length":11,"start":42,"text":"Seattle"}]}`
