### ISSUE TITLE
Implement Live Deidentification

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/phi-deidentifier#44]
Make it so the user doesn't have to touch the button (maybe every 400ms with no keystroke), to call the de-identify function.

**Comment by tschaffter** [comment]
My reason for canceling this ticket is that the de-identification could takes quite some time depending on the implementation. This can lead to confusing situation where the user would type again some text in the hope to trigger a response but would then just reset the request. Currently using a button to de-identify is more intuitive. We can also block the button to prevent overlapping requests.
