### ISSUE TITLE
Block External Networking

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/phi-deidentifier#68]
We need to make sure none of the annotators in the stack can exfiltrate data to an outside server.

**Comment by tschaffter** [comment]
You may find the solution before @thomasyu888 wakes up, otherwise he can tell you how he does in when evaluating the performance of a tool. Here we want all we want all the containers of the docker stack to not have access to internet.

**Comment by thomasyu888** [comment]
If you are using docker-compose you want to set up an internal network:

```yaml
networks:
  internal_network:
    internal: true
    driver: bridge
```

_I think_ that should work - i don't see `internal` documented  on the docker-compose network but i saw this post: https://forums.docker.com/t/internal-network-between-containers-without-external-network-access/41751/8.

If you aren't using docker-compose heres how do to it manaully:

```bash
docker network create --internal submission
docker run --network submission -d nlpsandbox/date-annotator-example:latest
docker run --network submission -d other/service/that/uses/annotator
```
