### ISSUE TITLE
Rely on the nlpsandbox-client

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/phi-deidentifier#69]
The Deidentifier should not just fail and give a 500 if it can't get a good response from one or more of the annotators

**Comment by tschaffter** [comment]
@cascadianblue Is this ticket about better try-catch block (e.g. use them around smaller chunk of code) and better error messages?

**Comment by cascadianblue** [comment]
If one of the annotators can't be reached or doesn't give a good response, how do we respond? We should probably propagate this to the front end, right?

**Comment by cascadianblue** [comment]
In the future, we could consume this tool: https://github.com/nlpsandbox/nlpsandbox-client

**Comment by tschaffter** [comment]
@cascadianblue As discussed, please create one ticket per improvement identifier.

**Comment by tschaffter** [comment]
@cascadianblue Can you please create individual tickets for each improvement that you have in mind? Then let's close this ticket because it's too generic.

**Comment by cascadianblue** [comment]
The main thing that would help with this would be making the PHI deidentifier server use [the NLP Sandbox Client](https://github.com/nlpsandbox/nlpsandbox-client) to make requests to the PHI Annotators

**Comment by tschaffter** [comment]
@cascadianblue The [version 0.3.1](https://github.com/nlpsandbox/nlpsandbox-client/releases/tag/0.3.1) of the client should work. If you have any question regarding using the client, please let @thomasyu888 and me know.
