### ISSUE TITLE
Fix '{}' is not of type 'object' - 'deidentificationSteps.0.annotationTypeMaskConfig'

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/phi-deidentifier#82]
#### Steps to reproduce the issue

1. `docker-compose up --build`
2. Go to localhost/ui
3. Test the deidentification endpoint using the default configuration

Error:

![image](https://user-images.githubusercontent.com/3056480/108000561-118f0180-6f9f-11eb-8d66-cfbaae7ca2fd.png)

```
{
  "detail": "'{}' is not of type 'object' - 'deidentificationSteps.0.annotationTypeMaskConfig'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

#### Expected behavior

The example note should be deidentified.

**Comment by cascadianblue** [comment]
I think this is a bug with how `openapi-generator-cli` generates the examples. Given our specification, it shouldn't be outputting a `{}` in the place where it is now outputting a `"{}"`.

I think the best work-around might be for me to provide an `example:` to [the `DeidentifyRequest` schema](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/phi-deidentifier/components/schemas/DeidentifyRequest.yaml#L6)

**Comment by tschaffter** [comment]
@cascadianblue Can you please submit a PR that address this issue?

**Comment by cascadianblue** [comment]
@tschaffter just did!
